import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BadgeCheck, Download, FileText, Headphones, MessageCircle, PackageCheck, RefreshCw, ShieldCheck, ShoppingBag, Store } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { ApiError, apiRequest, STAFF_ROLES } from "../api/client";
import { useAuth } from "../auth/AuthContext";
import { Seo } from "../components/Seo";

type Grant = { id: string; downloadCount: number; maxDownloads: number; expiresAt: string; productFile: { displayName: string; version: number } };
type Order = { id: string; orderNumber: string; invoiceNumber: string; status: string; totalCents: number; currency: string; createdAt: string; payment?: { method: string; status: string }; items: Array<{ id: string; productName: string; product: { slug: string; type: string }; downloadGrants: Grant[] }>; refunds: Array<{ status: string }>; disputes: Array<{ status: string }> };

export function AccountDashboardPage() {
  const { user, logout } = useAuth(); const navigate = useNavigate(); const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  useEffect(() => { void apiRequest<{ orders: Order[] }>("/api/commerce/orders").then((data) => setOrders(data.orders)).catch(() => undefined).finally(() => setLoading(false)); }, []);
  const downloads = useMemo(() => orders.flatMap((order) => order.items.flatMap((item) => item.downloadGrants.map((grant) => ({ order, item, grant })))), [orders]);
  async function signOut() { await logout(); navigate("/"); }
  async function requestRefund(order: Order) { const reason = window.prompt("Tell us what went wrong (at least 20 characters):"); if (!reason) return; try { await apiRequest(`/api/commerce/orders/${order.id}/refunds`, { method: "POST", body: { reason } }); setMessage("Refund request submitted. Support will review the order record."); } catch (error) { setMessage(error instanceof ApiError ? error.message : "Could not submit the request."); } }
  if (!user) return null;
  return <main className="account-page"><Seo title="Account dashboard" description="Manage HSello orders, downloads, invoices, support, and seller activity." /><nav className="account-nav"><Link className="brand-lockup" to="/"><span className="brand-glyph">H</span><span><strong>HSELLO</strong><small>MY EXCHANGE</small></span></Link><div><Link to="/catalog">Marketplace</Link><Link to="/support">Support</Link>{user.role === "SELLER" ? <Link to="/seller">Seller studio</Link> : null}{STAFF_ROLES.includes(user.role) ? <Link to="/admin">Admin</Link> : null}</div><button onClick={() => void signOut()}>Sign out</button></nav>
    <section className="account-hero"><div><span className="role-pill"><BadgeCheck /> {user.role.replace("_", " ")}</span><h1>Good to see you,<br />{user.firstName}.</h1><p>Orders, files, invoices, support, and seller work—kept in one place.</p></div><div className="account-profile"><span>{user.firstName[0]}{user.lastName[0]}</span><div><strong>{user.firstName} {user.lastName}</strong><small>@{user.username} · {user.email}</small></div><ShieldCheck /></div></section>
    {message ? <div className="dashboard-message">{message}</div> : null}
    <section className="account-metrics"><div><ShoppingBag /><span><strong>{orders.length}</strong><small>Total orders</small></span></div><div><Download /><span><strong>{downloads.length}</strong><small>Available files</small></span></div><div><Headphones /><span><strong>Every day</strong><small>Support coverage</small></span></div></section>
    <section className="account-content"><div className="account-orders"><header><div><span className="section-index">PURCHASES</span><h2>Orders & delivery</h2></div><Link to="/catalog">Keep browsing <ArrowRight /></Link></header>{loading ? <div className="empty-state">Loading purchases…</div> : orders.length ? orders.map((order) => <article className="order-card" key={order.id}><header><div><span className={`order-state ${order.status.toLowerCase()}`}>{order.status.replaceAll("_", " ")}</span><strong>{order.orderNumber}</strong><small>{new Date(order.createdAt).toLocaleDateString()} · {order.payment?.method.replaceAll("_", " ")}</small></div><b>${(order.totalCents/100).toFixed(2)} {order.currency}</b></header>{order.items.map((item) => <div className="order-item" key={item.id}><PackageCheck /><div><Link to={`/products/${item.product.slug}`}>{item.productName}</Link><small>{item.product.type === "SERVICE" ? "Service delivery workspace" : `${item.downloadGrants.length} downloadable file${item.downloadGrants.length === 1 ? "" : "s"}`}</small></div>{item.product.type === "SERVICE" ? <Link to={`/orders/${order.id}`}><MessageCircle /> Open delivery</Link> : item.downloadGrants.map((grant) => <a key={grant.id} href={`/api/commerce/downloads/${grant.id}`}><Download /> {grant.productFile.displayName} v{grant.productFile.version} <small>{grant.maxDownloads-grant.downloadCount} left</small></a>)}</div>)}<footer><a href={`/api/commerce/orders/${order.id}/invoice`}><FileText /> Invoice {order.invoiceNumber}</a><Link to={`/orders/${order.id}`}><MessageCircle /> Order chat</Link><button disabled={Boolean(order.refunds.length)} onClick={() => void requestRefund(order)}><RefreshCw /> {order.refunds.length ? `Refund ${order.refunds[0].status.toLowerCase()}` : "Request refund"}</button><Link to="/support"><Headphones /> Get help</Link></footer></article>) : <div className="dashboard-empty"><PackageCheck /><h3>No orders yet</h3><p>When you buy something, its invoice, delivery, and support history will live here.</p><Link className="primary-link" to="/catalog">Explore products <ArrowRight /></Link></div>}</div>
      <aside className="account-side"><section><span className="section-index">DOWNLOAD LIBRARY</span><h2>Latest files</h2>{downloads.slice(0,5).map(({ item, grant }) => <a href={`/api/commerce/downloads/${grant.id}`} key={grant.id}><Download /><span><strong>{item.productName}</strong><small>{grant.productFile.displayName} · v{grant.productFile.version}</small></span><ArrowRight /></a>)}{!downloads.length ? <p>No files have been released yet.</p> : null}</section><section><span className="section-index">SELL ON HSELLO</span><Store /><h2>{user.role === "SELLER" ? "Your seller studio" : "Have original work?"}</h2><p>{user.role === "SELLER" ? "Manage product files, submissions, orders, and buyer responses." : "Apply for a verified store. Every product is reviewed before it goes live."}</p><Link to={user.role === "SELLER" ? "/seller" : "/seller/apply"}>{user.role === "SELLER" ? "Open seller studio" : "Start seller application"} <ArrowRight /></Link></section></aside>
    </section>
  </main>;
}
