import { ArrowLeft, ArrowRight, BookOpen, Clock3 } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { MarketFooter, MarketHeader } from "../components/MarketHeader";
import { Seo } from "../components/Seo";

const posts = [
  { slug: "evaluate-a-digital-product", tag: "BUYING WELL", title: "How to evaluate a digital product before checkout", excerpt: "A practical way to read licenses, delivery promises, reviews, update terms, and seller policies.", time: "6 min", color: "lime", sections: [["Start with the deliverable", "A trustworthy listing names the files, formats, compatibility, license, delivery method, and support window. Treat vague promises as missing information, not as benefits."], ["Read proof in context", "Verified reviews matter, but so do recency, specific comments, seller responses, and whether the feedback describes the same use case you have."], ["Keep the transaction protected", "Pay only through checkout and keep service delivery in the order record. That gives support a reliable timeline if the result differs from the listing."]] },
  { slug: "write-a-trustworthy-product-page", tag: "SELLER FIELD GUIDE", title: "Writing a product page buyers can actually trust", excerpt: "Specific descriptions reduce disputes. Here’s what to include without turning the page into legal soup.", time: "8 min", color: "violet", sections: [["Name the outcome and the contents", "Explain who the product helps, what is included, what software or knowledge it requires, and what is explicitly not included."], ["Make terms scannable", "Put delivery time, update policy, license scope, refund constraints, and support window near the buying decision rather than burying them."], ["Use original evidence", "Show your own screenshots and realistic examples. Avoid borrowed brand marks, unverifiable claims, fake scarcity, and performance guarantees."]] },
  { slug: "why-account-trading-is-prohibited", tag: "TRUST & SAFETY", title: "Why HSello does not allow account or credential trading", excerpt: "The practical security, consent, fraud, and ownership problems behind the line we draw.", time: "5 min", color: "coral", sections: [["Credentials are not ordinary goods", "An account can expose private messages, payment methods, identity data, and recovery channels. A transfer can also violate the originating service’s rules."], ["Ownership is difficult to prove", "Screenshots do not establish durable control. Recovery disputes often harm both the buyer and an unrelated original owner."], ["Safer products exist", "Creators can sell original templates, education, workflows, audits, and licensed assets without transferring a third party identity or access token."]] },
  { slug: "versioning-digital-downloads", tag: "CREATOR OPERATIONS", title: "A calm versioning strategy for digital downloads", excerpt: "How to ship useful updates while keeping existing customers informed and supported.", time: "7 min", color: "cyan", sections: [["Version for buyers, not machinery", "Use a short version number, date, and plain-language change note. Buyers should know whether they need to download the update."], ["Preserve important history", "Keep the current supported file obvious while retaining prior versions only when compatibility makes them useful."], ["Set expectations before checkout", "State whether buyers receive future updates, for how long, and whether a major new edition will be a separate product."]] }
] as const;

export function BlogPage() {
  const { slug } = useParams();
  const selected = slug ? posts.find((post) => post.slug === slug) : undefined;
  if (slug && !selected) return <main className="commerce-page"><Seo title="Guide not found" description="This marketplace guide does not exist." robots="noindex,follow" /><MarketHeader /><section className="not-found-page"><h1>Guide not found.</h1><Link to="/blog"><ArrowLeft /> Return to field notes</Link></section><MarketFooter /></main>;
  if (selected) return <main className="commerce-page"><Seo title={selected.title} description={selected.excerpt} canonicalPath={`/blog/${selected.slug}`} /><MarketHeader /><article className="blog-article"><Link to="/blog"><ArrowLeft /> All field notes</Link><small>{selected.tag}</small><h1>{selected.title}</h1><p className="blog-lead">{selected.excerpt}</p><span><Clock3 /> {selected.time} read</span>{selected.sections.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}</article><MarketFooter /></main>;
  return <main className="commerce-page"><Seo title="Marketplace field notes" description="Practical guides for buying, selling, licensing, delivery, and trust in digital marketplaces." canonicalPath="/blog" /><MarketHeader /><section className="blog-hero"><BookOpen /><span className="section-index">FIELD NOTES</span><h1>Better digital trade,<br />explained plainly.</h1><p>Guides for buyers, sellers, and people who have read enough vague marketplace advice for one lifetime.</p></section><section className="blog-grid">{posts.map((post, index) => <article className={`blog-card tone-${post.color}`} key={post.slug}><span>0{index + 1}</span><small>{post.tag}</small><h2>{post.title}</h2><p>{post.excerpt}</p><footer><span><Clock3 /> {post.time} read</span><Link to={`/blog/${post.slug}`}>Read guide <ArrowRight /></Link></footer></article>)}</section><MarketFooter /></main>;
}
