import { ArrowRight, BadgeCheck, BookOpen, CheckCircle2, Headphones, Search, ShieldCheck, ShoppingBag, Sparkles, Star, Store, Zap } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { STAFF_ROLES } from "../api/client";
import { useAuth } from "../auth/AuthContext";
import { useCart } from "../commerce/CartContext";
import { MarketFooter } from "../components/MarketHeader";
import { Seo } from "../components/Seo";
import { useMarketplaceCategories, useMarketplaceProducts } from "../commerce/useMarketplace";
import { LocaleSwitcher } from "../components/LocaleSwitcher";
import { useLocale } from "../i18n/LocaleContext";

export function MarketplaceLandingPage() {
  const { t } = useLocale();
  const { user } = useAuth(); const { add, count } = useCart(); const navigate = useNavigate(); const [query, setQuery] = useState("");
  const productState = useMarketplaceProducts();
  const categoryState = useMarketplaceCategories();
  const homeCategories = useMemo(() => categoryState.categories.filter((category) => !category.parentSlug).slice(0, 9), [categoryState.categories]);
  const products = useMemo(() => productState.products.filter((product) => !query.trim() || `${product.title} ${product.category} ${product.seller}`.toLowerCase().includes(query.toLowerCase())).slice(0, 6), [query, productState.products]);
  const accountPath = user ? (STAFF_ROLES.includes(user.role) ? "/admin" : "/dashboard") : "/sign-in";
  function search(event: FormEvent) { event.preventDefault(); document.querySelector("#home-products")?.scrollIntoView({ behavior: "smooth" }); }
  return <main className="marketplace-shell"><Seo title="Original digital products, protected" description="A reviewed marketplace for templates, creative assets, AI workflows, game assets, and expert services from verified sellers." canonicalPath="/" schema={{ "@context": "https://schema.org", "@type": "WebSite", name: "HSello", url: location.origin, potentialAction: { "@type": "SearchAction", target: `${location.origin}/catalog?q={search_term_string}`, "query-input": "required name=search_term_string" } }} />
    <div className="announcement-bar"><span><ShieldCheck size={14} /> Buyer protection on every order</span><span className="announcement-center">Original work. <strong>No account trading.</strong></span><span>Human support <Headphones size={14} /></span></div>
    <header className="market-header"><Link className="brand-lockup" to="/"><span className="brand-glyph">H</span><span><strong>HSELLO</strong><small>DIGITAL EXCHANGE</small></span></Link><nav className="market-nav"><a href="#home-categories">{t("categories")}</a><a href="#home-products">{t("releases")}</a><Link to="/blog">{t("notes")}</Link><a href="#sell-safe">{t("sell")}</a></nav><div className="header-actions"><LocaleSwitcher /><Link className="header-signin" to="/cart">{t("cart")} ({count})</Link><Link className="header-join" to={accountPath}>{user ? t("account") : t("signIn")}</Link></div></header>
    <section className="market-hero safe-hero"><div className="hero-copy-block"><div className="hero-kicker"><span className="live-dot" /> Reviewed products · verified sellers</div><h1>THE DIGITAL<br /><em>MARKET,</em> CLEANED UP.</h1><p>Original templates, creative assets, useful workflows, game resources, and expert services—sold with clear licenses and protected delivery.</p><form className="hero-search" onSubmit={search}><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("search")} /><button>{t("explore")} <ArrowRight /></button></form><div className="popular-searches"><span>Popular:</span>{homeCategories.slice(0, 4).map((category) => <Link to={`/categories/${category.slug}`} key={category.slug}>{category.name}</Link>)}</div></div>
      <div className="hero-market-card safe-market-card"><div className="pulse-heading"><span>MARKET PRINCIPLES</span><span className="pulse-live"><i /> ENFORCED</span></div><div className="safe-card-mark"><ShieldCheck /><strong>Useful things.<br />Clear provenance.</strong><p>Every listing is reviewed before publishing. Downloads stay protected. Services stay inside an order record.</p></div><div className="market-ticker"><div><span>PRODUCT REVIEW</span><strong>100%</strong><small>before publishing</small></div><div><span>GREY-MARKET ACCOUNTS</span><strong>0</strong><small>explicitly prohibited</small></div></div><div className="recent-trades"><span>Built into every order</span>{["Secure payment confirmation", "Time-limited digital delivery", "Refunds, disputes & human support"].map((item) => <div key={item}><CheckCircle2 /><span>{item}</span><small>ready</small></div>)}</div></div>
    </section>
    <section className="trust-strip"><div><ShieldCheck /><span><strong>Protected payment</strong><small>Provider confirmation before delivery</small></span></div><div><BadgeCheck /><span><strong>Verified sellers</strong><small>Identity and store review</small></span></div><div><Zap /><span><strong>Controlled delivery</strong><small>Expiring links and download limits</small></span></div><div><Headphones /><span><strong>Human support</strong><small>Tickets, refunds, and disputes</small></span></div></section>
    <section className="market-section categories-section" id="home-categories"><div className="market-section-heading"><div><span className="section-index">01 / CURATED DIRECTORY</span><h2>Digital goods worth keeping</h2></div><p>Focused categories with useful context—and firm lines around fraud, credentials, and stolen work.</p></div>{categoryState.loading ? <div className="product-skeleton-grid" aria-label="Loading categories" aria-busy="true">{Array.from({ length: 6 }, (_, index) => <span key={index} />)}</div> : categoryState.error ? <div className="status-panel error" role="alert"><strong>Categories could not be loaded.</strong><span>{categoryState.error}</span><button type="button" onClick={categoryState.retry}>Try again</button></div> : homeCategories.length ? <div className="safe-category-grid">{homeCategories.map((category, index) => <Link to={`/categories/${category.slug}`} className={`safe-category tone-${["violet","coral","blue","lime","amber","cyan"][index % 6]}`} key={category.slug}><span>{String(index + 1).padStart(2, "0")}</span><Sparkles /><h3>{category.name}</h3><p>{category.description}</p><ArrowRight /></Link>)}</div> : <div className="no-results"><Search /><strong>No categories published yet</strong><span>Check back when the first curated listings go live.</span></div>}</section>
    <section className="market-section offers-section" id="home-products"><div className="market-section-heading offers-heading"><div><span className="section-index">02 / REVIEWED RELEASES</span><h2>Made by people who stand behind it</h2></div><Link className="view-all-button" to="/catalog">View all <ArrowRight /></Link></div>{productState.loading ? <div className="product-skeleton-grid" aria-label="Loading products" aria-busy="true">{Array.from({ length: 6 }, (_, index) => <span key={index} />)}</div> : productState.error ? <div className="status-panel error" role="alert"><strong>Products could not be loaded.</strong><span>{productState.error}</span><button type="button" onClick={productState.retry}>Try again</button></div> : products.length ? <div className="catalog-product-grid home-product-grid">{products.map((product) => <article key={product.id}><Link className="catalog-product-art" to={`/products/${product.slug}`}>{product.imageUrl ? <img src={product.imageUrl} alt="" loading="lazy" width="640" height="480" /> : <b>{product.icon}</b>}<span>{product.badge}</span></Link><div><span>{product.category}</span><Link to={`/products/${product.slug}`}><h2>{product.title}</h2></Link><p>{product.description}</p><div className="catalog-rating"><Star fill="currentColor" /> {product.rating} <small>({product.reviews})</small></div><footer><strong>${(product.priceCents/100).toFixed(2)}</strong><button type="button" onClick={() => { add(product); navigate("/cart"); }}><ShoppingBag /> Add</button></footer></div></article>)}</div> : <div className="no-results"><Search /><strong>{query ? "No close matches" : "No products published yet"}</strong><span>{query ? "Try a broader phrase or browse the full catalog." : "Approved products will appear here when they are published."}</span></div>}</section>
    <section className="how-section"><div className="how-intro"><span className="section-index">03 / HOW IT WORKS</span><h2>Three steps.<br />No mystery meat.</h2><p>Clear product terms, controlled payment, and a delivery record when it matters.</p></div><div className="how-steps"><div><span>01</span><Search /><h3>Read the real terms</h3><p>Compare license, delivery, seller policy, ratings, and verified reviews.</p></div><div><span>02</span><ShieldCheck /><h3>Pay securely</h3><p>Use hosted Stripe or PayPal, or a staff-approved alternative method.</p></div><div><span>03</span><CheckCircle2 /><h3>Receive and retain</h3><p>Access downloads, updates, invoices, chat, support, and refund tools.</p></div></div></section>
    <section className="seller-cta" id="sell-safe"><div className="seller-orbit"><Store /><span /><span /></div><div><span className="section-index">FOR ORIGINAL CREATORS</span><h2>Sell the work you’re proud to put your name on.</h2><p>Versioned files, protected delivery, verified reviews, service chat, and clear enforcement.</p></div><div className="seller-cta-actions"><Link to="/seller/apply">Apply to sell <ArrowRight /></Link><Link to="/seller-policy"><BookOpen /> Read seller policy</Link></div></section><MarketFooter />
  </main>;
}
