import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, BadgeCheck, BarChart3, Boxes, ChevronRight, CircleDollarSign, Download, FileText, FolderPlus, Gavel, Headphones, LayoutTemplate, LogOut, PackageCheck, RefreshCw, Search, ShieldAlert, Store, Tag, TicketCheck, UserRoundX, Users } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { ApiError, apiRequest, type Role, type SellerApplication } from "../api/client";
import { useAuth } from "../auth/AuthContext";
import { Seo } from "../components/Seo";

type Tab = "overview" | "sellers" | "products" | "users" | "orders" | "payments" | "refunds" | "disputes" | "tickets" | "categories" | "coupons" | "reports" | "homepage";
type Overview = Record<"pendingSellers"|"pendingProducts"|"openTickets"|"openDisputes"|"refundRequests"|"awaitingPayments"|"users"|"orders", number>;
type AdminUser = { id:string; firstName:string; lastName:string; email:string; username:string; role:Role; emailVerified:boolean; isSuspended:boolean; suspensionReason?:string };
type Product = { id:string; name:string; status:string; priceCents:number; rejectionReason?:string; category:{name:string}; files:Array<{id:string}>; seller:{id:string;email:string;username:string;sellerProfile?:{storeName:string;isSuspended:boolean}} };
type Order = { id:string;orderNumber:string;invoiceNumber:string;status:string;totalCents:number;currency:string;createdAt:string;buyer:{firstName:string;lastName:string;email:string};payment?:{id:string;method:string;status:string};items:Array<{id:string;productName:string}> };
type Refund = { id:string;status:string;amountCents:number;reason:string;createdAt:string;order:{orderNumber:string;payment?:{method:string}};requestedBy:{email:string} };
type Dispute = { id:string;status:string;subject:string;description:string;createdAt:string;order:{orderNumber:string};openedBy:{email:string} };
type Ticket = { id:string;ticketNumber:string;status:string;category:string;subject:string;updatedAt:string;creator:{email:string};messages:Array<{id:string;body:string;isInternal:boolean;author:{firstName:string;role:string}}> };
type Category = { id:string;name:string;slug:string;description:string;isActive:boolean;sortOrder:number };
type Coupon = { id:string;code:string;percentOff?:number;amountOffCents?:number;redemptionCount:number;maxRedemptions?:number;isActive:boolean;expiresAt?:string };
type Report = { id:string;status:string;reason:string;details?:string;createdAt:string;adminNotes?:string;product:{name:string;slug:string;status:string};reporter:{email:string} };

const nav: Array<{id:Tab;label:string;icon:typeof BarChart3}> = [
  {id:"overview",label:"Overview",icon:BarChart3},{id:"sellers",label:"Seller applications",icon:Store},{id:"products",label:"Product review",icon:Boxes},{id:"users",label:"Users & sellers",icon:Users},{id:"orders",label:"All orders",icon:PackageCheck},{id:"payments",label:"Payment approval",icon:CircleDollarSign},{id:"refunds",label:"Refunds",icon:RefreshCw},{id:"disputes",label:"Disputes",icon:Gavel},{id:"tickets",label:"Support tickets",icon:Headphones},{id:"categories",label:"Categories",icon:FolderPlus},{id:"coupons",label:"Coupons",icon:Tag},{id:"reports",label:"Safety reports",icon:ShieldAlert},{id:"homepage",label:"Homepage",icon:LayoutTemplate}
];

export function OperationsAdminPage() {
  const { user, logout } = useAuth(); const navigate = useNavigate(); const [tab,setTab]=useState<Tab>("overview"); const [busy,setBusy]=useState(""); const [message,setMessage]=useState(""); const [search,setSearch]=useState("");
  const [overview,setOverview]=useState<Overview|null>(null); const [applications,setApplications]=useState<SellerApplication[]>([]); const [products,setProducts]=useState<Product[]>([]); const [users,setUsers]=useState<AdminUser[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [refunds,setRefunds]=useState<Refund[]>([]); const [disputes,setDisputes]=useState<Dispute[]>([]); const [tickets,setTickets]=useState<Ticket[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [coupons,setCoupons]=useState<Coupon[]>([]); const [reports,setReports]=useState<Report[]>([]);
  const load = useCallback(async () => { setMessage(""); try { const paths:Partial<Record<Tab,string>>={overview:"/api/admin/overview",sellers:"/api/admin/seller-applications",products:"/api/admin/products",users:"/api/admin/users",orders:"/api/admin/orders",payments:"/api/admin/orders",refunds:"/api/admin/refunds",disputes:"/api/admin/disputes",tickets:"/api/admin/tickets",categories:"/api/admin/categories",coupons:"/api/admin/coupons",reports:"/api/admin/reports",homepage:"/api/admin/homepage"}; const data=await apiRequest<Record<string,unknown>>(paths[tab]!); if(tab==="overview")setOverview(data.overview as Overview); if(tab==="sellers")setApplications(data.applications as SellerApplication[]); if(tab==="products")setProducts(data.products as Product[]); if(tab==="users")setUsers(data.users as AdminUser[]); if(tab==="orders"||tab==="payments")setOrders(data.orders as Order[]); if(tab==="refunds")setRefunds(data.refunds as Refund[]); if(tab==="disputes")setDisputes(data.disputes as Dispute[]); if(tab==="tickets")setTickets(data.tickets as Ticket[]); if(tab==="categories")setCategories(data.categories as Category[]); if(tab==="coupons")setCoupons(data.coupons as Coupon[]); if(tab==="reports")setReports(data.reports as Report[]); } catch(error){setMessage(error instanceof ApiError?error.message:"Could not load this workspace.");} },[tab]);
  useEffect(()=>{void load();},[load]);
  const act=async(id:string,path:string,body:Record<string,unknown>)=>{setBusy(id);setMessage("");try{await apiRequest(path,{method:"PATCH",body});setMessage("Change saved.");await load();}catch(error){setMessage(error instanceof ApiError?error.message:"Action failed.");}finally{setBusy("");}};
  const post=async(id:string,path:string,body:Record<string,unknown>={})=>{setBusy(id);setMessage("");try{await apiRequest(path,{method:"POST",body});setMessage("Action completed.");await load();}catch(error){setMessage(error instanceof ApiError?error.message:"Action failed.");}finally{setBusy("");}};
  const filteredUsers=useMemo(()=>users.filter((entry)=>`${entry.firstName} ${entry.lastName} ${entry.email} ${entry.username}`.toLowerCase().includes(search.toLowerCase())),[search,users]);
  return <main className="ops-admin"><Seo title="Administration" description="HSello operations, moderation, payments, support, and marketplace controls." /><aside className="ops-sidebar"><Link className="brand-lockup" to="/"><span className="brand-glyph">H</span><span><strong>HSELLO</strong><small>OPERATIONS</small></span></Link><nav>{nav.map(({id,label,icon:Icon})=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><Icon />{label}<ChevronRight /></button>)}</nav><div className="admin-sidebar-footer"><div><span>{user?.firstName[0]}{user?.lastName[0]}</span><div><strong>{user?.firstName} {user?.lastName}</strong><small>{user?.role.replace("_"," ")}</small></div></div><button className="secondary-button" onClick={async () => { await logout(); navigate("/"); }}><LogOut /> Sign out</button></div></aside>
    <section className="ops-main"><header className="ops-topbar"><div><Link to="/dashboard"><ArrowLeft /> Account</Link><span>/</span><strong>{nav.find((item)=>item.id===tab)?.label}</strong></div><button onClick={()=>void load()}><RefreshCw /> Refresh</button></header><div className="ops-heading"><span className="section-index">STAFF WORKSPACE</span><h1>{nav.find((item)=>item.id===tab)?.label}</h1><p>Review context, take action, and leave a clean operational record.</p></div>{message?<div className={`ops-message ${message.includes("failed")||message.includes("Could not")?"error":""}`}>{message}</div>:null}
      {tab==="overview"&&<OverviewPanel overview={overview} onOpen={setTab} />}
      {tab==="sellers"&&<section className="ops-grid">{applications.map((app)=><article className="ops-card" key={app.id}><header><div><span className="store-avatar">{app.storeName.slice(0,2).toUpperCase()}</span><div><h2>{app.storeName}</h2><p>{app.fullLegalName} · {app.email}</p></div></div><Status value={app.status}/></header><p>{app.storeDescription}</p><dl><div><dt>Location</dt><dd>{app.city}, {app.country}</dd></div><div><dt>Categories</dt><dd>{app.productCategories.join(", ")}</dd></div></dl><footer><button className="approve" disabled={busy===app.id} onClick={()=>void act(app.id,`/api/admin/seller-applications/${app.id}`,{status:"APPROVED"})}><BadgeCheck/>Approve</button><button className="danger" disabled={busy===app.id} onClick={()=>void act(app.id,`/api/admin/seller-applications/${app.id}`,{status:"REJECTED",adminNotes:window.prompt("Reason for rejection")||"Application does not meet seller requirements."})}><AlertTriangle/>Reject</button></footer></article>)}</section>}
      {tab==="products"&&<section className="ops-table"><div className="ops-row ops-row-head"><span>Product</span><span>Seller</span><span>Review</span><span>Actions</span></div>{products.map((product)=><div className="ops-row" key={product.id}><div><strong>{product.name}</strong><small>{product.category.name} · ${(product.priceCents/100).toFixed(2)} · {product.files.length} files</small></div><div><strong>{product.seller.sellerProfile?.storeName??product.seller.username}</strong><small>{product.seller.email}</small></div><Status value={product.status}/><div className="row-actions"><button onClick={()=>void act(product.id,`/api/admin/products/${product.id}/status`,{status:"APPROVED"})}>Approve</button><button onClick={()=>void act(product.id,`/api/admin/products/${product.id}/status`,{status:"REJECTED",reason:window.prompt("Rejection reason")||"Listing needs revision."})}>Reject</button><button className="danger" onClick={()=>void act(product.id,`/api/admin/products/${product.id}/status`,{status:"REMOVED",reason:window.prompt("Removal reason")||"Removed under marketplace policy."})}>Remove</button></div></div>)}</section>}
      {tab==="users"&&<><div className="ops-search"><Search/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search users"/></div><section className="ops-table"><div className="ops-row ops-row-head"><span>User</span><span>Role</span><span>Verification</span><span>Actions</span></div>{filteredUsers.map((entry)=><div className="ops-row" key={entry.id}><div><strong>{entry.firstName} {entry.lastName}</strong><small>@{entry.username} · {entry.email}</small></div><Status value={entry.role}/><span>{entry.emailVerified?"Email verified":"Unverified"}</span><div className="row-actions"><button className={entry.isSuspended?"approve":"danger"} onClick={()=>void act(entry.id,`/api/admin/users/${entry.id}/suspension`,{suspended:!entry.isSuspended,reason:entry.isSuspended?undefined:window.prompt("Suspension reason")||"Suspended by marketplace operations."})}>{entry.isSuspended?"Restore account":"Suspend user"}</button>{entry.role==="SELLER"?<button className="danger" onClick={()=>void act(`seller-${entry.id}`,`/api/admin/sellers/${entry.id}/suspension`,{suspended:true,reason:window.prompt("Store suspension reason")||"Store suspended for review."})}>Suspend store</button>:null}</div></div>)}</section></>}
      {(tab==="orders"||tab==="payments")&&<section className="ops-table"><div className="ops-row ops-row-head"><span>Order</span><span>Buyer</span><span>Payment</span><span>Total / action</span></div>{orders.filter((order)=>tab==="orders"||order.payment?.status==="REQUIRES_ACTION").map((order)=><div className="ops-row" key={order.id}><div><strong>{order.orderNumber}</strong><small>{order.invoiceNumber} · {new Date(order.createdAt).toLocaleDateString()}</small></div><div><strong>{order.buyer.firstName} {order.buyer.lastName}</strong><small>{order.buyer.email}</small></div><div><Status value={order.payment?.status??order.status}/><small>{order.payment?.method.replaceAll("_"," ")}</small></div><div className="row-actions"><strong>${(order.totalCents/100).toFixed(2)}</strong>{tab==="payments"&&order.payment?<button className="approve" onClick={()=>void post(order.payment!.id,`/api/admin/payments/${order.payment!.id}/approve`)}>Approve payment</button>:null}</div></div>)}</section>}
      {tab==="refunds"&&<section className="ops-grid">{refunds.map((refund)=><article className="ops-card" key={refund.id}><header><div><CircleDollarSign/><div><h2>${(refund.amountCents/100).toFixed(2)} refund</h2><p>{refund.order.orderNumber} · {refund.requestedBy.email}</p></div></div><Status value={refund.status}/></header><p>{refund.reason}</p><footer><button className="approve" onClick={()=>void act(refund.id,`/api/admin/refunds/${refund.id}`,{status:"COMPLETED",adminNotes:"Approved after staff review."})}>Complete refund</button><button className="danger" onClick={()=>void act(refund.id,`/api/admin/refunds/${refund.id}`,{status:"REJECTED",adminNotes:window.prompt("Reason")||"Request did not meet refund policy."})}>Reject</button></footer></article>)}</section>}
      {tab==="disputes"&&<section className="ops-grid">{disputes.map((dispute)=><article className="ops-card" key={dispute.id}><header><div><Gavel/><div><h2>{dispute.subject}</h2><p>{dispute.order.orderNumber} · {dispute.openedBy.email}</p></div></div><Status value={dispute.status}/></header><p>{dispute.description}</p><footer><button onClick={()=>void act(dispute.id,`/api/admin/disputes/${dispute.id}`,{status:"UNDER_REVIEW"})}>Take review</button><button className="approve" onClick={()=>void act(dispute.id,`/api/admin/disputes/${dispute.id}`,{status:"RESOLVED_BUYER",resolution:window.prompt("Resolution")||"Resolved in the buyer’s favor."})}>Resolve buyer</button><button onClick={()=>void act(dispute.id,`/api/admin/disputes/${dispute.id}`,{status:"RESOLVED_SELLER",resolution:window.prompt("Resolution")||"Resolved in the seller’s favor."})}>Resolve seller</button></footer></article>)}</section>}
      {tab==="tickets"&&<section className="ops-grid">{tickets.map((ticket)=><article className="ops-card ticket-card" key={ticket.id}><header><div><TicketCheck/><div><h2>{ticket.subject}</h2><p>{ticket.ticketNumber} · {ticket.creator.email}</p></div></div><Status value={ticket.status}/></header><div className="ticket-preview">{ticket.messages.slice(-2).map((entry)=><p key={entry.id}><strong>{entry.author.firstName}</strong> {entry.body}</p>)}</div><footer><button onClick={()=>{const body=window.prompt("Reply to this ticket");if(body)void post(ticket.id,`/api/admin/tickets/${ticket.id}/reply`,{body,status:"PENDING",isInternal:false});}}>Reply</button><button className="approve" onClick={()=>void post(ticket.id,`/api/admin/tickets/${ticket.id}/reply`,{body:"This ticket has been resolved. Reply if you still need help.",status:"RESOLVED",isInternal:false})}>Resolve</button></footer></article>)}</section>}
      {tab==="categories"&&<><CreateCategory onDone={load}/><section className="ops-table"><div className="ops-row ops-row-head"><span>Category</span><span>Slug</span><span>Status</span><span>Order</span></div>{categories.map((category)=><div className="ops-row" key={category.id}><div><strong>{category.name}</strong><small>{category.description}</small></div><code>{category.slug}</code><Status value={category.isActive?"ACTIVE":"HIDDEN"}/><strong>{category.sortOrder}</strong></div>)}</section></>}
      {tab==="coupons"&&<><CreateCoupon onDone={load}/><section className="ops-table"><div className="ops-row ops-row-head"><span>Code</span><span>Discount</span><span>Usage</span><span>Status</span></div>{coupons.map((coupon)=><div className="ops-row" key={coupon.id}><strong>{coupon.code}</strong><span>{coupon.percentOff?`${coupon.percentOff}%`:`$${((coupon.amountOffCents??0)/100).toFixed(2)}`}</span><span>{coupon.redemptionCount} / {coupon.maxRedemptions??"∞"}</span><Status value={coupon.isActive?"ACTIVE":"INACTIVE"}/></div>)}</section></>}
      {tab==="reports"&&<section className="ops-grid">{reports.map((report)=><article className="ops-card" key={report.id}><header><div><ShieldAlert/><div><h2>{report.product.name}</h2><p>{report.reporter.email} · {report.reason}</p></div></div><Status value={report.status}/></header><p>{report.details||"No additional details."}</p><footer><button onClick={()=>void act(report.id,`/api/admin/reports/${report.id}`,{status:"DISMISSED",adminNotes:"Reviewed; no policy violation found."})}>Dismiss</button><button className="danger" onClick={()=>void act(report.id,`/api/admin/reports/${report.id}`,{status:"ACTIONED",removeProduct:true,adminNotes:window.prompt("Removal note")||"Product violates marketplace policy."})}>Remove product</button></footer></article>)}</section>}
      {tab==="homepage"&&<HomepageEditor onDone={load}/>} 
      {!message&&((tab==="sellers"&&!applications.length)||(tab==="products"&&!products.length)||(tab==="refunds"&&!refunds.length)||(tab==="disputes"&&!disputes.length)||(tab==="tickets"&&!tickets.length)||(tab==="reports"&&!reports.length))?<div className="ops-empty"><BadgeCheck/><h2>Queue clear</h2><p>Nothing needs action in this workspace right now.</p></div>:null}
    </section></main>;
}

function Status({value}:{value:string}){return <span className={`ops-status ${value.toLowerCase()}`}>{value.replaceAll("_"," ")}</span>}
function OverviewPanel({overview,onOpen}:{overview:Overview|null;onOpen:(tab:Tab)=>void}){const cards=[{key:"pendingSellers",label:"Seller applications",tab:"sellers",icon:Store},{key:"pendingProducts",label:"Product reviews",tab:"products",icon:Boxes},{key:"awaitingPayments",label:"Payments to approve",tab:"payments",icon:CircleDollarSign},{key:"refundRequests",label:"Refund requests",tab:"refunds",icon:RefreshCw},{key:"openDisputes",label:"Open disputes",tab:"disputes",icon:Gavel},{key:"openTickets",label:"Support tickets",tab:"tickets",icon:Headphones},{key:"users",label:"Marketplace users",tab:"users",icon:Users},{key:"orders",label:"Total orders",tab:"orders",icon:PackageCheck}] as const;return <><section className="overview-grid">{cards.map(({key,label,tab,icon:Icon})=><button onClick={()=>onOpen(tab)} key={key}><Icon/><span>{label}</span><strong>{overview?.[key]??"—"}</strong><ChevronRight/></button>)}</section><section className="ops-export"><div><FileText/><span><strong>Order report</strong><small>CSV export for finance and operations.</small></span></div><a href="/api/admin/export/orders.csv"><Download/>Export orders</a></section></>}
function CreateCategory({onDone}:{onDone:()=>Promise<void>}){const[name,setName]=useState("");const[description,setDescription]=useState("");async function submit(event:FormEvent){event.preventDefault();await apiRequest("/api/admin/categories",{method:"POST",body:{name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),description,sortOrder:0}});setName("");setDescription("");await onDone();}return <form className="ops-create" onSubmit={submit}><div><FolderPlus/><span><strong>Create category</strong><small>Add a useful SEO landing page to the catalog.</small></span></div><input required minLength={2} value={name} onChange={(event)=>setName(event.target.value)} placeholder="Category name"/><input required minLength={20} value={description} onChange={(event)=>setDescription(event.target.value)} placeholder="Useful category description"/><button>Create</button></form>}
function CreateCoupon({onDone}:{onDone:()=>Promise<void>}){const[code,setCode]=useState("");const[percent,setPercent]=useState("10");async function submit(event:FormEvent){event.preventDefault();await apiRequest("/api/admin/coupons",{method:"POST",body:{code,percentOff:Number(percent),minimumCents:0,maxRedemptions:100}});setCode("");await onDone();}return <form className="ops-create" onSubmit={submit}><div><Tag/><span><strong>Create coupon</strong><small>Percentage discount with a redemption cap.</small></span></div><input required minLength={3} value={code} onChange={(event)=>setCode(event.target.value.toUpperCase())} placeholder="CODE"/><input required type="number" min="1" max="100" value={percent} onChange={(event)=>setPercent(event.target.value)} /><button>Create</button></form>}
function HomepageEditor({onDone}:{onDone:()=>Promise<void>}){const[title,setTitle]=useState("Original digital products, protected end to end.");const[subtitle,setSubtitle]=useState("Reviewed products. Verified sellers. Clear delivery.");const[body,setBody]=useState("Templates, assets, workflows, and expert services without the grey market.");async function submit(event:FormEvent){event.preventDefault();await apiRequest("/api/admin/homepage/hero",{method:"PUT",body:{title,subtitle,body,ctaLabel:"Explore marketplace",ctaUrl:"/catalog",isVisible:true,sortOrder:0}});await onDone();}return <form className="homepage-editor" onSubmit={submit}><div><LayoutTemplate/><span><strong>Homepage hero</strong><small>Published content is returned by the content API.</small></span></div><label><span>Headline</span><input value={title} onChange={(event)=>setTitle(event.target.value)}/></label><label><span>Subtitle</span><input value={subtitle} onChange={(event)=>setSubtitle(event.target.value)}/></label><label><span>Body</span><textarea rows={5} value={body} onChange={(event)=>setBody(event.target.value)}/></label><button>Publish section</button></form>}
