import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, FileUp, PackagePlus, Send, Store, Upload } from "lucide-react";
import { Link } from "react-router-dom";
import { ApiError, apiRequest } from "../api/client";
import { Seo } from "../components/Seo";

type Category = { id: string; name: string };
type Product = { id: string; name: string; status: string; type: string; priceCents: number; rejectionReason?: string; files: Array<{ id: string; displayName: string; version: number; sizeBytes: number }> };

export function SellerWorkspacePage() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ categoryId: "", name: "", shortDescription: "", description: "", type: "DOWNLOAD", price: "", deliveryNote: "", downloadLimit: 5, downloadExpiryHours: 168, buyersGetUpdates: true });
  const load = () => Promise.all([apiRequest<{ products: Product[] }>("/api/seller/products"), apiRequest<{ categories: Category[] }>("/api/marketplace/categories")]).then(([a,b]) => { setProducts(a.products); setCategories(b.categories); if (!form.categoryId && b.categories[0]) setForm((current) => ({ ...current, categoryId: b.categories[0].id })); });
  useEffect(() => { void load().catch(() => undefined); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { await apiRequest("/api/seller/products", { method: "POST", body: { ...form, priceCents: Math.round(Number(form.price)*100), currency: "USD", coverImageUrl: null, compareAtPriceCents: null, seoTitle: form.name, seoDescription: form.shortDescription } }); setOpen(false); setMessage("Draft created. Upload the delivery file, then submit it for review."); await load(); } catch (error) { setMessage(error instanceof ApiError ? error.message : "Product could not be created."); } finally { setBusy(false); } }
  async function upload(productId: string, file?: File) { if (!file) return; const data = new FormData(); data.append("file", file); setMessage("Uploading product file…"); try { await apiRequest(`/api/seller/products/${productId}/files`, { method: "POST", body: data }); setMessage("New file version uploaded."); await load(); } catch (error) { setMessage(error instanceof ApiError ? error.message : "File upload failed."); } }
  async function submit(productId: string) { try { await apiRequest(`/api/seller/products/${productId}/submit`, { method: "POST" }); setMessage("Product submitted for staff review."); await load(); } catch (error) { setMessage(error instanceof ApiError ? error.message : "Product could not be submitted."); } }
  return <main className="seller-workspace"><Seo title="Seller studio" description="Manage HSello store products, files, review submissions, and digital delivery." /><nav><Link to="/dashboard"><ArrowLeft /> Account</Link><strong><Store /> Seller studio</strong><button onClick={() => setOpen(true)}><PackagePlus /> New product</button></nav><header><span className="section-index">VERIFIED SELLER WORKSPACE</span><h1>Ship good work.<br />Keep it current.</h1><p>Product changes return to review. New file versions remain available to eligible previous buyers.</p></header>{message ? <div className="dashboard-message">{message}</div> : null}<section className="seller-product-list"><div className="seller-list-heading"><span>Product</span><span>Status</span><span>Files</span><span>Actions</span></div>{products.length ? products.map((product) => <article key={product.id}><div><span className="seller-product-mark">{product.name[0]}</span><div><strong>{product.name}</strong><small>{product.type} · ${(product.priceCents/100).toFixed(2)}</small>{product.rejectionReason ? <p>{product.rejectionReason}</p> : null}</div></div><span className={`status-pill ${product.status.toLowerCase()}`}>{product.status}</span><div className="file-versions">{product.files.length ? product.files.map((file) => <span key={file.id}>{file.displayName} <small>v{file.version}</small></span>) : <small>No files</small>}</div><div><label className="upload-action"><Upload /> Upload update<input type="file" onChange={(event) => void upload(product.id, event.target.files?.[0])} /></label>{["DRAFT","REJECTED"].includes(product.status) ? <button onClick={() => void submit(product.id)}><Send /> Submit review</button> : null}</div></article>) : <div className="dashboard-empty"><FileUp /><h2>No products yet</h2><p>Create a draft, upload its delivery file, and submit it for review.</p></div>}</section>
    {open ? <div className="modal-backdrop"><form className="seller-product-form" onSubmit={create}><button type="button" className="modal-close" onClick={() => setOpen(false)}>×</button><span className="section-index">NEW PRODUCT DRAFT</span><h2>Describe the work clearly.</h2><div className="form-grid two"><label><span>Name</span><input required minLength={3} value={form.name} onChange={(event) => setForm({...form,name:event.target.value})} /></label><label><span>Category</span><select required value={form.categoryId} onChange={(event) => setForm({...form,categoryId:event.target.value})}>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label><span>Type</span><select value={form.type} onChange={(event) => setForm({...form,type:event.target.value})}><option value="DOWNLOAD">Digital download</option><option value="SERVICE">Service</option></select></label><label><span>Price (USD)</span><input required type="number" min="0.50" step="0.01" value={form.price} onChange={(event) => setForm({...form,price:event.target.value})} /></label></div><label><span>Short description</span><input required minLength={10} maxLength={240} value={form.shortDescription} onChange={(event) => setForm({...form,shortDescription:event.target.value})} /></label><label><span>Full description</span><textarea required minLength={30} rows={6} value={form.description} onChange={(event) => setForm({...form,description:event.target.value})} /></label><label><span>Delivery note</span><textarea rows={3} value={form.deliveryNote} onChange={(event) => setForm({...form,deliveryNote:event.target.value})} /></label><button className="primary-button" disabled={busy}><PackagePlus /> {busy ? "Creating…" : "Create draft"}</button></form></div> : null}
  </main>;
}
